name: CI

on:
  push:
    branches: [main, dev]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_and_lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Read node version from `.nvmrc` file
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - uses: actions/setup-node@v3
        with:
          # use the output from the action
          node-version: '${{ steps.nvmrc.outputs.node_version }}'

      - name: Install `node_modules`
        run: npm install

      - name: Tests
        run: npm run test

      - name: Linting
        run: npm run lint

      - name: Prettier
        run: npm run prettier:check
